#!/system/bin/sh

export PATH=$PATH:/system/xbin:/sbin:/vendor/bin:/system/sbin:/system/bin
if [ -d "/data/local/busybox*/xbin" ]; then
	export PATH=$PATH:`ls -d /data/local/busybox*/xbin 2>/dev/null`;
fi

LOG=/data/local/init.log;

if [ -e $LOG ]; then
	rm $LOG;
fi;

touch $LOG;
echo "# LOGGING ENGINE" > $LOG;
##Re-Mount /system, /data and /cache for better performance
sync

busybox sleep 2

#while true ; do
#	if [ "0`getprop sys.boot_completed`" -ne "0" ] ; then
#		break
#	else
#		echo "Wait..."
#	fi
#done

#
# Print Startup Banner
#

M=`getprop ro.product.model`
V=`getprop ro.product.version`
L="log -p i -t cm"
$L "**************************************";
$L "          KoolKit sysinit";
$L "        init.d & userinit.d";
$L "        Support environment";
$L "       " $M
$L "       " $V
$L "**************************************";

##Check for system write access and grant if read only##
##Log results to /data/local/init.log##
if [ -w /system ] ; then

	echo "/system is already Read/Write" $( date +"%m-%d-%Y %H:%M:%S" ) >> $LOG;
	$L "/system is already Read/Write" $( date +"%m-%d-%Y %H:%M:%S" )
else
	echo "Applying Read/Write access to /system" $( date +"%m-%d-%Y %H:%M:%S" ) >> $LOG;
	$L "Applying Read/Write access to /system" $( date +"%m-%d-%Y %H:%M:%S" )
	mount -o remount,rw /system
fi

##Apply execute Privileges to init folders##
##And run all init scripts in init.d folder##
##Once completed run all scripts in userinit.d folder##
##the caviat is that init.d MUST exist if init.d,##
##folder is missing sysinit will error out and exit##
##this prevents userinit.d from running since it is##
##dependant on init.d scripts completing first.##

if [ -d /system/etc/init.d ] ; then
	chmod 0755 /system/etc/init.d
	chmod -R 0777 /system/etc/init.d/*
	logwrapper run-parts /system/etc/init.d/
else
	echo "!!Warning!! No init.d support exiting" $( date +"%m-%d-%Y %H:%M:%S" ) >> $LOG;
	$L "!!Warning!! No init.d support exiting" $( date +"%m-%d-%Y %H:%M:%S" )
	exit 1
fi

if [ -d /system/etc/userinit.d ] ; then
	chmod 0755 /system/etc/userinit.d
	chmod -R 0777 /system/etc/userinit.d/*
	logwrapper run-parts /system/etc/userinit.d/
else
	echo "!!Warning!! No userinit.d support exiting" $( date +"%m-%d-%Y %H:%M:%S" ) >> $LOG;
	$L "!!Warning!! No userinit.d support exiting" $( date +"%m-%d-%Y %H:%M:%S" )
	exit 1
fi

exit 0
